In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder,LabelEncoder 
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [3]:
df=pd.read_csv('Bengaluru_House_Data.csv')
df

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK      NaN       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK      NaN       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK      NaN       3600   5.0      NaN  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK      NaN        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [4]:
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [5]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [6]:
prop = df.drop(['area_type','society','availability'], axis=1)

In [7]:
prop.head()

location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [8]:
prop.shape

(13320, 6)

In [9]:
prop['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [10]:
prop['location']=prop['location'].fillna('Electronic City')

In [11]:
prop['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [12]:
prop['size']=prop['size'].fillna('2 BHK')

In [13]:
prop['bath'].value_counts()

2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: bath, dtype: int64

In [14]:
prop['bath'] = prop['bath'].fillna(prop['bath'].median())

In [15]:
prop['balcony_was_missing'] = prop['balcony'].isna()
prop['balcony'] = prop['balcony'].fillna(2)

In [16]:
prop.isna().sum()

location               0
size                   0
total_sqft             0
bath                   0
balcony                0
price                  0
balcony_was_missing    0
dtype: int64

In [17]:
prop['size'] = prop['size'].replace(['1 RK'],'0 BRK')

In [18]:
prop['No_of_bedrooms'] = prop['size'].str.split().str.get(0).astype(int)
prop.head()

location       size total_sqft  bath  balcony   price  \
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07   
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00   
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00   
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00   
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00   

   balcony_was_missing  No_of_bedrooms  
0                False               2  
1                False               4  
2                False               3  
3                False               3  
4                False               2

In [19]:
prop[prop.No_of_bedrooms>20]

location        size total_sqft  bath  balcony  price  \
1718  2Electronic City Phase II      27 BHK       8000  27.0      0.0  230.0   
4684                Munnekollal  43 Bedroom       2400  40.0      0.0  660.0   

      balcony_was_missing  No_of_bedrooms  
1718                False              27  
4684                False              43

In [20]:
prop = prop.drop([1718,4684])

In [21]:
prop['total_sqft'].value_counts()

1200    843
1100    221
1500    205
2400    195
600     180
       ... 
3580      1
2461      1
1437      1
2155      1
4689      1
Name: total_sqft, Length: 2117, dtype: int64

In [22]:
def convert_range(x):
    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0])+float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [23]:
prop['total_sqft'] = prop['total_sqft'].apply(convert_range)

In [24]:
prop['price_per_sqft'] = prop['price']*100000/prop['total_sqft']

In [25]:
prop.drop('size',inplace=True,axis=1)

In [26]:
prop['location'] = prop['location'].apply(lambda x: x.strip())
loc_num = prop.groupby('location')['location'].agg('count').sort_values(ascending=False)
loc_num

location
Whitefield               541
Sarjapur  Road           399
Electronic City          305
Kanakpura Road           273
Thanisandra              237
                        ... 
1 Giri Nagar               1
Kanakapura Road,           1
Kanakapura main  Road      1
Karnataka Shabarimala      1
whitefiled                 1
Name: location, Length: 1293, dtype: int64

In [27]:
low = loc_num[loc_num<=10]
low

location
Gunjur Palya             10
Sector 1 HSR Layout      10
Dodsworth Layout         10
1st Block Koramangala    10
Dairy Circle             10
                         ..
1 Giri Nagar              1
Kanakapura Road,          1
Kanakapura main  Road     1
Karnataka Shabarimala     1
whitefiled                1
Name: location, Length: 1052, dtype: int64

In [28]:
prop.location = prop.location.apply(lambda x: 'other' if x in low else x)

In [29]:
temp = pd.get_dummies(prop.location)
df = pd.concat([prop.drop('location',axis=1),temp],axis=True)
df = df.fillna(0)
df.head()

total_sqft  bath  balcony   price  balcony_was_missing  No_of_bedrooms  \
0      1056.0   2.0      1.0   39.07                False               2   
1      2600.0   5.0      3.0  120.00                False               4   
2      1440.0   2.0      3.0   62.00                False               3   
3      1521.0   3.0      1.0   95.00                False               3   
4      1200.0   2.0      1.0   51.00                False               2   

   price_per_sqft  1st Block Jayanagar  1st Phase JP Nagar  \
0     3699.810606                    0                   0   
1     4615.384615                    0                   0   
2     4305.555556                    0                   0   
3     6245.890861                    0                   0   
4     4250.000000                    0                   0   

   2nd Phase Judicial Layout  2nd Stage Nagarbhavi  5th Block Hbr Layout  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     0                     0   
3                          0                     0                     0   
4                          0                     0                     0   

   5th Phase JP Nagar  6th Phase JP Nagar  7th Phase JP Nagar  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   8th Phase JP Nagar  9th Phase JP Nagar  AECS Layout  Abbigere  \
0                   0                   0            0         0   
1                   0                   0            0         0   
2                   0                   0            0         0   
3                   0                   0            0         0   
4                   0                   0            0         0   

   Akshaya Nagar  Ambalipura  Ambedkar Nagar  Amruthahalli  Anandapura  \
0              0           0               0             0           0   
1              0           0               0             0           0   
2              0           0               0             0           0   
3              0           0               0             0           0   
4              0           0               0             0           0   

   Ananth Nagar  Anekal  Anjanapura  Ardendale  Arekere  Attibele  \
0             0       0           0          0        0         0   
1             0       0           0          0        0         0   
2             0       0           0          0        0         0   
3             0       0           0          0        0         0   
4             0       0           0          0        0         0   

   BEML Layout  BTM 2nd Stage  BTM Layout  Babusapalaya  Badavala Nagar  \
0            0              0           0             0               0   
1            0              0           0             0               0   
2            0              0           0             0               0   
3            0              0           0             0               0   
4            0              0           0             0               0   

   Balagere  Banashankari  Banashankari Stage II  Banashankari Stage III  \
0         0             0                      0                       0   
1         0             0                      0                       0   
2         0             0                      0                       0   
3         0             0                      0                       0   
4         0             0                      0                       0   

   Banashankari Stage V  Banashankari Stage VI  Banaswadi  Banjara Layout  \
0                     0                      0          0        

In [30]:
#data preprocessing
X = df.drop(['price'], axis=1)
y = df['price']

In [31]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X,y,test_size=0.2,random_state=42)

In [32]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)


LinearRegression()

In [33]:
lr.coef_

array([ 4.60627282e-02,  3.73108669e+01, -2.44805191e+00,  4.46077983e+01,
       -6.49774865e+00,  1.76601804e-05,  7.38967629e+01,  3.54063402e+01,
       -2.51133308e+01,  6.72783835e+01,  2.62671848e+01, -1.99908943e+01,
        5.50620981e+00, -4.50197734e-01, -1.89518301e+01, -2.39753212e+01,
       -2.23991183e+01, -5.06011592e+01, -2.03930843e+01,  2.04104040e+00,
        2.49278854e+01, -1.43986642e+00, -3.10365738e+01, -3.18455542e+01,
       -1.84101108e+01, -2.67636571e+01, -2.30474922e+01, -7.94022061e+00,
       -1.08053262e+01, -6.46762246e-01,  4.15816328e+01, -3.08034050e+00,
       -2.48620978e+01, -5.49247681e-01,  2.29464011e+00,  7.93002038e+00,
        8.83688104e+01, -2.18868506e+01, -3.21246997e+01, -2.09362719e+01,
        1.79775289e+01, -3.98886807e+01, -1.63277393e+01, -6.83280440e+00,
        5.84392351e+01,  6.02386082e+01, -2.81150824e+01, -3.59882363e+01,
       -3.13471728e+01, -1.38775050e+01,  1.21162574e+02, -1.86587893e+01,
       -2.10488327e+01, -

In [34]:
lr.intercept_

-39.87962624531542

In [35]:
lr.predict(X_test)

array([ 29.73520798, 103.47726493, 299.47598001, ...,  98.75134557,
       104.88367018,  88.80593656])

In [36]:
y_test

9299      42.295
4192      88.000
10002    265.000
3964      68.000
3335      90.000
          ...   
10014    220.000
9142     111.000
1972      56.000
2609      65.000
3791      51.770
Name: price, Length: 2664, dtype: float64

In [37]:
lr.score(X_test,y_test)

0.4841052529822567

In [38]:
# Ridge Regression
from sklearn.linear_model import Ridge ,Lasso
from sklearn.model_selection import GridSearchCV

In [39]:
rd=Ridge(alpha=3)
rd.fit(X_train,y_train)

Ridge(alpha=3)

In [40]:
rd.score(X_test,y_test)

0.48489836085735605

In [41]:
ls=Lasso(alpha=25)
ls.fit(X_train,y_train)
ls.score(X_test,y_test)

0.44715805720456137

### Modal Evaluation 

### Root Mean Square

In [42]:
ypred=lr.predict(X_test)
ypred

array([ 29.73520798, 103.47726493, 299.47598001, ...,  98.75134557,
       104.88367018,  88.80593656])

In [43]:
y_test

9299      42.295
4192      88.000
10002    265.000
3964      68.000
3335      90.000
          ...   
10014    220.000
9142     111.000
1972      56.000
2609      65.000
3791      51.770
Name: price, Length: 2664, dtype: float64

In [44]:
from sklearn.metrics import mean_squared_error

In [45]:
mse=mean_squared_error(y_test,ypred)
root=np.sqrt(mse)
print('MSE',mse)
print('RMSE',root)

MSE 12278.272258576662
RMSE 110.80736554298483


### So from the Prediction and accuracy we will not use linear Regression because There is huge Difference prediction of value 

In [46]:
# R- square implemet
from sklearn.metrics import r2_score

In [47]:
r2_score(y_test,ypred)

0.4841052529822567

In [48]:
#Polynomial Liner Regression

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [50]:
pg=PolynomialFeatures(degree=2)
pg.fit(X_train)


PolynomialFeatures()

In [51]:
x_train_poly=pg.transform(X_train)
x_test_poly=pg.transform(X_test)

In [ ]:
lr=LinearRegression()
lr.fit(x_train_poly,y_train)

In [ ]:
lr.score(x_test_poly,y_test)

In [ ]:
ypred1=lr.predict(x_test_poly)
ypred1

In [ ]:
y_test

In [ ]:
lr.score(x_test_poly,y_test)

In [ ]:
mse=mean_squared_error(y_test,ypred1)
root=np.sqrt(mse)

print(mse,root)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(random_state=0)
dt.fit(X_train, y_train)
dpred=dt.predict(X_test)


In [ ]:
dt.score(X_test,y_test)

In [ ]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,dpred)
print('R2_Score =',r2)
roc=roc_auc_score(y_test,dpred)
print('Roc_Auc_Score=',roc)
f1=f1_score(y_test,dpred)
print('f1_score =',f1)
# Now Plot roc graph  
fpr, tpr, thresholds=roc_curve(y_test,dpred)
plt.plot(fpr, tpr)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.show()


In [83]:
import pickle

In [84]:
#Save the model
filename='House_price_prid'
pickle.dump(dt,open(filename,'wb'))

In [85]:
loaded_model=pickle.load(open(filename,'rb'))
loaded_model.predict(X_test)

array([ 43.7 ,  87.5 , 260.  , ...,  56.  ,  65.  ,  51.77])

In [88]:
y_test

9299      42.295
4192      88.000
10002    265.000
3964      68.000
3335      90.000
          ...   
10014    220.000
9142     111.000
1972      56.000
2609      65.000
3791      51.770
Name: price, Length: 2664, dtype: float64

# 